### ISSUE TITLE
Competitive TF2 6v6 issues

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/comp_6v6_bugs#1]
Updated list of reported bugs that affect the competitive play of Team Fortress 2, 6v6.
If you have a Github account, please add a :+1: reaction to each of these posts. (Top right, +😊 button)

# Bug Reports
- [ ] ValveSoftware/Source-1-Games#2084 Class limit bypass
- [ ] ValveSoftware/Source-1-Games#2185 Sticky detonation delay
- [ ] ValveSoftware/Source-1-Games#2466 Wallbugs
- [ ] ValveSoftware/Source-1-Games#2486 Splash bug
- [ ] ValveSoftware/Source-1-Games#2487 Random pistol spread
- [x] ValveSoftware/Source-1-Games#2488 showpanel exploit
- [ ] ValveSoftware/Source-1-Games#2489 Fall damage random spread
- [ ] ValveSoftware/Source-1-Games#2620 Uber builds during pauses

# Feature Requests
- [ ] ValveSoftware/Source-1-Games#2079 Server-enforced first-person taunts
- [ ] ValveSoftware/Source-1-Games#2484 Legalize viewmodel offsets
- [ ] ValveSoftware/Source-1-Games#2490 -tickrate option
- [ ] ValveSoftware/Source-1-Games#2491 Projectile hitting teammates

**Comment by ldesgoui** [comment]
https://github.com/ValveSoftware/Source-1-Games/issues/2185

**Comment by ldesgoui** [comment]
TODO:
pipes are random
disable all cosmetics *for the sake of performance*
item info box showable/selectable by slot during spectating
pyro should have reduced self-damage
disguised spy should be affected by explosions (like airblast affects him)
spy should use its disguise hitbox when attacked

https://forums.alliedmods.net/showthread.php?p=1671299
https://docs.google.com/document/pub?id=1URgEtYCsqdpFdbWPMNqNJIZngSbUUCCtSQ03AuHrcBE

**Comment by ldesgoui** [comment]
self-damage resistance is ufced

**Comment by ldesgoui** [comment]
See https://github.com/ldesgoui/tf2-comp-fixes
